import { Test, TestOverview } from '@/lib/api/dto/test';

export const mockTests: TestOverview[] = [
    {
        id: '1',
        title: 'IELTS Academic Reading Practice Test 1',
        created_at: '2024-01-15T10:30:00Z',
        skill: 'Reading',
        number_participant: 30,
        comments: 12,
        duration: 60,
    },
    {
        id: '2',
        title: 'IELTS General Writing Task 1 & 2',
        created_at: '2024-01-14T14:20:00Z',
        skill: 'Writing',
        number_participant: 70,
        comments: 5,
        duration: 60,
    },
    {
        id: '3',
        title: 'IELTS Listening Mock Test - Academic',
        created_at: '2024-01-13T09:15:00Z',
        skill: 'Listening',
        number_participant: 26,
        comments: 8,
        duration: 30,
    },
    {
        id: '4',
        title: 'IELTS Speaking Part 1, 2 & 3 Practice',
        created_at: '2024-01-12T16:45:00Z',
        skill: 'Speaking',
        number_participant: 39,
        comments: 15,
        duration: 15,
    },
    {
        id: '5',
        title: 'IELTS Academic Writing Task 1 - Graphs',
        created_at: '2024-01-11T11:00:00Z',
        skill: 'Writing',
        number_participant: 40,
        comments: 3,
        duration: 20,
    },
    {
        id: '6',
        title: 'IELTS Reading - True/False/Not Given Focus',
        created_at: '2024-01-10T13:30:00Z',
        skill: 'Reading',
        number_participant: 120,
        comments: 10,
        duration: 45,
    },
    ...Array.from({ length: 14 }).map((_, idx) => ({
        id: 'idx + 7',
        title: `Extra Mock Test ${idx + 7}`,
        created_at: '2024-01-09T10:00:00Z',
        skill: ['Reading', 'Writing', 'Listening', 'Speaking'][idx % 4],
        number_participant: Math.floor(Math.random() * 150),
        comments: Math.floor(Math.random() * 20),
        duration: [15, 30, 45, 60][idx % 4],
    })),
];

export const testData: Test = {
    id: 'listening-test-001',
    title: 'IELTS Listening Practice Test 1',
    duration: 30,
    number_sections: 4,
    number_questions: 40,
    number_participant: 1247,
    section: [
        {
            id: 'section-1',
            title: 'Section 1',
            questions: 10,
            description: 'Conversation in everyday social context',
        },
        {
            id: 'section-2',
            title: 'Section 2',
            questions: 10,
            description: 'Monologue in everyday social context',
        },
        {
            id: 'section-3',
            title: 'Section 3',
            questions: 10,
            description: 'Conversation in educational context',
        },
        {
            id: 'section-4',
            title: 'Section 4',
            questions: 10,
            description: 'Monologue on academic subject',
        },
    ],
};
