import { Room } from '@/lib/api/dto/room';

export const sampleRooms: Room[] = [
    {
        id: '1',
        roomName: 'Deep Work Study Group',
        description: 'Focus on deep work sessions with like-minded learners',
        roomCode: 'DW2024',
        isPrivate: false,
        createdBy: 'user-1',
        numberOfMembers: 12,
        createdAt: '2025-11-01T08:00:00.000Z',
        members: [],
    },
    {
        id: '2',
        roomName: 'Morning Productivity Club',
        description: 'Early birds studying together from 6-9 AM',
        roomCode: 'MPC789',
        isPrivate: false,
        createdBy: 'user-2',
        numberOfMembers: 8,
        createdAt: '2025-11-02T06:00:00.000Z',
        members: [],
    },
    {
        id: '3',
        roomName: 'CS Study Session',
        description: 'Computer Science students preparing for finals',
        roomCode: 'CS5012',
        isPrivate: true,
        createdBy: 'user-3',
        numberOfMembers: 15,
        createdAt: '2025-11-03T14:00:00.000Z',
        members: [],
    },
    {
        id: '4',
        roomName: 'Language Learning Hub',
        description: 'Polyglots practicing and studying together',
        roomCode: 'LANG88',
        isPrivate: false,
        createdBy: 'user-4',
        numberOfMembers: 20,
        createdAt: '2025-11-04T10:00:00.000Z',
        members: [],
    },
    {
        id: '5',
        roomName: 'Night Owls Study Den',
        description: 'Late night study sessions for night owls',
        roomCode: 'NIGHT1',
        isPrivate: false,
        createdBy: 'user-5',
        numberOfMembers: 6,
        createdAt: '2025-11-05T22:00:00.000Z',
        members: [],
    },
    {
        id: '6',
        roomName: 'Medical Students United',
        description: 'Med students studying anatomy and pathology',
        roomCode: 'MED456',
        isPrivate: true,
        createdBy: 'user-6',
        numberOfMembers: 18,
        createdAt: '2025-11-06T09:00:00.000Z',
        members: [],
    },
    {
        id: '7',
        roomName: 'Law School Prep',
        description: 'LSAT preparation and law school study sessions',
        roomCode: 'LAW123',
        isPrivate: false,
        createdBy: 'user-7',
        numberOfMembers: 11,
        createdAt: '2025-11-07T13:00:00.000Z',
        members: [],
    },
    {
        id: '8',
        roomName: 'MBA Candidates',
        description: 'Business school students tackling case studies',
        roomCode: 'MBA999',
        isPrivate: false,
        createdBy: 'user-8',
        numberOfMembers: 14,
        createdAt: '2025-11-08T11:00:00.000Z',
        members: [],
    },
    {
        id: '9',
        roomName: 'Engineering Study Hall',
        description: 'Engineering students working on problem sets',
        roomCode: 'ENG567',
        isPrivate: false,
        createdBy: 'user-9',
        numberOfMembers: 22,
        createdAt: '2025-11-09T15:00:00.000Z',
        members: [],
    },
    {
        id: '10',
        roomName: 'Art History Enthusiasts',
        description: 'Discussing and studying art movements and history',
        roomCode: 'ART234',
        isPrivate: false,
        createdBy: 'user-10',
        numberOfMembers: 7,
        createdAt: '2025-11-10T16:00:00.000Z',
        members: [],
    },
    {
        id: '11',
        roomName: 'Psychology Research Group',
        description: 'Psychology majors researching and studying together',
        roomCode: 'PSY890',
        isPrivate: true,
        createdBy: 'user-11',
        numberOfMembers: 13,
        createdAt: '2025-11-11T10:00:00.000Z',
        members: [],
    },
    {
        id: '12',
        roomName: 'Math Olympiad Training',
        description: 'Advanced mathematics problem solving sessions',
        roomCode: 'MATH12',
        isPrivate: false,
        createdBy: 'user-12',
        numberOfMembers: 9,
        createdAt: '2025-11-12T14:00:00.000Z',
        members: [],
    },
    {
        id: '13',
        roomName: 'Physics Research Lab',
        description: 'Physics students working on quantum mechanics',
        roomCode: 'PHY456',
        isPrivate: false,
        createdBy: 'user-13',
        numberOfMembers: 16,
        createdAt: '2025-11-13T09:00:00.000Z',
        members: [],
    },
    {
        id: '14',
        roomName: 'Chemistry Study Group',
        description: 'Organic chemistry students studying reactions',
        roomCode: 'CHEM78',
        isPrivate: false,
        createdBy: 'user-14',
        numberOfMembers: 10,
        createdAt: '2025-11-14T12:00:00.000Z',
        members: [],
    },
    {
        id: '15',
        roomName: 'Biology Lab Partners',
        description: 'Biology students preparing for lab practicals',
        roomCode: 'BIO345',
        isPrivate: true,
        createdBy: 'user-15',
        numberOfMembers: 12,
        createdAt: '2025-11-15T08:00:00.000Z',
        members: [],
    },
    {
        id: '16',
        roomName: 'Philosophy Discussion Circle',
        description: 'Exploring existentialism and modern philosophy',
        roomCode: 'PHIL90',
        isPrivate: false,
        createdBy: 'user-16',
        numberOfMembers: 8,
        createdAt: '2025-11-16T17:00:00.000Z',
        members: [],
    },
    {
        id: '17',
        roomName: 'History Buffs United',
        description: 'World history and civilization studies',
        roomCode: 'HIST12',
        isPrivate: false,
        createdBy: 'user-17',
        numberOfMembers: 11,
        createdAt: '2025-11-17T10:00:00.000Z',
        members: [],
    },
    {
        id: '18',
        roomName: 'Economics Discussion Forum',
        description: 'Macro and microeconomics study group',
        roomCode: 'ECON56',
        isPrivate: false,
        createdBy: 'user-18',
        numberOfMembers: 15,
        createdAt: '2025-11-18T13:00:00.000Z',
        members: [],
    },
    {
        id: '19',
        roomName: 'Creative Writing Workshop',
        description: "Writers sharing and critiquing each other's work",
        roomCode: 'WRITE9',
        isPrivate: false,
        createdBy: 'user-19',
        numberOfMembers: 6,
        createdAt: '2025-11-19T18:00:00.000Z',
        members: [],
    },
    {
        id: '20',
        roomName: 'Architecture Design Studio',
        description: 'Architecture students working on design projects',
        roomCode: 'ARCH45',
        isPrivate: true,
        createdBy: 'user-20',
        numberOfMembers: 14,
        createdAt: '2025-11-20T11:00:00.000Z',
        members: [],
    },
    {
        id: '21',
        roomName: 'Music Theory Study',
        description: 'Learning music theory and composition',
        roomCode: 'MUSIC7',
        isPrivate: false,
        createdBy: 'user-21',
        numberOfMembers: 9,
        createdAt: '2025-11-21T15:00:00.000Z',
        members: [],
    },
    {
        id: '22',
        roomName: 'Film Studies Analysis',
        description: 'Analyzing cinema and film techniques',
        roomCode: 'FILM23',
        isPrivate: false,
        createdBy: 'user-22',
        numberOfMembers: 10,
        createdAt: '2025-11-22T19:00:00.000Z',
        members: [],
    },
    {
        id: '23',
        roomName: 'Data Science Bootcamp',
        description: 'Machine learning and data analysis study group',
        roomCode: 'DATA99',
        isPrivate: false,
        createdBy: 'user-23',
        numberOfMembers: 19,
        createdAt: '2025-11-23T09:00:00.000Z',
        members: [],
    },
    {
        id: '24',
        roomName: 'Web Development Workshop',
        description: 'Full-stack development learning together',
        roomCode: 'WEB567',
        isPrivate: false,
        createdBy: 'user-24',
        numberOfMembers: 21,
        createdAt: '2025-11-24T14:00:00.000Z',
        members: [],
    },
    {
        id: '25',
        roomName: 'Marketing Strategy Study',
        description: 'Digital marketing and brand strategy discussions',
        roomCode: 'MARK88',
        isPrivate: false,
        createdBy: 'user-25',
        numberOfMembers: 13,
        createdAt: '2025-11-25T12:00:00.000Z',
        members: [],
    },
];
