import { AmbientSound } from '@/lib/api/dto/room';

export const BACKGROUND_IMAGES = [
    '/room-bg-1.jpg',
    '/room-bg-2.jpg',
    '/room-bg-3.jpg',
    '/room-bg-4.jpg',
    '/room-bg-5.jpg',
    '/room-bg-6.jpg',
    '/room-bg-7.jpg',
    '/room-bg-8.jpg',
];

export const POMODORO_PRESETS = [
    { name: 'Classic Pomodoro', focus: 25, shortBreak: 5, longBreak: 15 },
    { name: 'Extended Focus', focus: 50, shortBreak: 10, longBreak: 20 },
    { name: 'Quick Sessions', focus: 15, shortBreak: 3, longBreak: 10 },
    { name: 'Custom', focus: 25, shortBreak: 5, longBreak: 15 },
];

export const AMBIENT_SOUNDS: AmbientSound[] = [
    {
        id: 'rain',
        name: 'Rain',
        icon: '🌧️',
        category: 'weather',
        enabled: false,
        volume: 50,
    },
    {
        id: 'birds',
        name: 'Birds',
        icon: '🐦',
        category: 'weather',
        enabled: false,
        volume: 50,
    },
    {
        id: 'bubbles',
        name: 'Bubbles',
        icon: '🫧',
        category: 'weather',
        enabled: false,
        volume: 50,
    },
    {
        id: 'campfire',
        name: 'Campfire',
        icon: '🏕️',
        category: 'weather',
        enabled: false,
        volume: 50,
    },
    {
        id: 'fire',
        name: 'Fire',
        icon: '🔥',
        category: 'weather',
        enabled: false,
        volume: 50,
    },
    // Nature
    {
        id: 'night',
        name: 'Night',
        icon: '🌙',
        category: 'nature',
        enabled: false,
        volume: 50,
    },
    {
        id: 'thunder',
        name: 'Thunder',
        icon: '⚡',
        category: 'nature',
        enabled: false,
        volume: 50,
    },
    {
        id: 'tractor',
        name: 'Tractor',
        icon: '🚜',
        category: 'nature',
        enabled: false,
        volume: 50,
    },
    {
        id: 'water',
        name: 'Water',
        icon: '💧',
        category: 'nature',
        enabled: false,
        volume: 50,
    },
    {
        id: 'ocean',
        name: 'Ocean',
        icon: '🌊',
        category: 'nature',
        enabled: false,
        volume: 50,
    },
    // Ambiance
    {
        id: 'heart-red',
        name: 'Heart Beat',
        icon: '❤️',
        category: 'ambiance',
        enabled: false,
        volume: 50,
    },
    {
        id: 'heart-pink',
        name: 'Pink Noise',
        icon: '💗',
        category: 'ambiance',
        enabled: false,
        volume: 50,
    },
    {
        id: 'heart-gray',
        name: 'White Noise',
        icon: '🤍',
        category: 'ambiance',
        enabled: false,
        volume: 50,
    },
    {
        id: 'pencil',
        name: 'Pencil',
        icon: '✏️',
        category: 'ambiance',
        enabled: false,
        volume: 50,
    },
    {
        id: 'mouse',
        name: 'Mouse Click',
        icon: '🖱️',
        category: 'ambiance',
        enabled: false,
        volume: 50,
    },
    // Workspace
    {
        id: 'keyboard',
        name: 'Keyboard',
        icon: '⌨️',
        category: 'workspace',
        enabled: false,
        volume: 50,
    },
    {
        id: 'notepad',
        name: 'Notepad',
        icon: '📝',
        category: 'workspace',
        enabled: false,
        volume: 50,
    },
    {
        id: 'tools',
        name: 'Tools',
        icon: '🔧',
        category: 'workspace',
        enabled: false,
        volume: 50,
    },
    {
        id: 'building',
        name: 'Building',
        icon: '🏢',
        category: 'workspace',
        enabled: false,
        volume: 50,
    },
    {
        id: 'coffee',
        name: 'Coffee Shop',
        icon: '☕',
        category: 'workspace',
        enabled: false,
        volume: 50,
    },
    {
        id: 'train',
        name: 'Train',
        icon: '🚆',
        category: 'workspace',
        enabled: false,
        volume: 50,
    },
    {
        id: 'fan',
        name: 'Fan',
        icon: '💨',
        category: 'workspace',
        enabled: false,
        volume: 50,
    },
];
